utils:
  file_manager : https://github.com/not-gitmodules/notgitmodules-file-manager-py
  file_encryptor : https://github.com/not-gitmodules/notgitmodules-file-encryptor-py
  hashicorp_loader: https://github.com/not-gitmodules/notgitmodules-hashicorp-loader

#services:
#  ip_locator_service: <github-url>